services:
    _defaults:
        autowire: true
        autoconfigure: true

    srebb_supervisor.locator:
        class: 'Symfony\Component\DependencyInjection\ServiceLocator'
        arguments:
            - []
        tags: ['container.service_locator']

    Srebb\Bundle\SupervisorBundle\Server\ServerFactory:

    Srebb\Bundle\SupervisorBundle\Server\ServerContainer:
        public: true
        bind:
            $globalUpdateInterval: '%srebb_supervisor.update_interval%'
            $serverList: '%srebb_supervisor.server_list%'
        autowire: true
        autoconfigure: true

    Srebb\Bundle\SupervisorBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']
